[build]
builder = "nixpacks"

[deploy]
startCommand = "python run.py"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "always"

[environment]
PORT = "5000"
FLASK_ENV = "production"
