[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn run:app --bind 0.0.0.0:$PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "always"

[environment]
FLASK_ENV = "production"
RAILWAY_ENVIRONMENT = "true"
